M48
; DRILL file {KiCad (6.0.0-0)} date 2022 January 07, Friday 13:34:19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-01-07T13:34:19+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.8031Y-3.4646
X4.8031Y-5.2362
X7.2441Y-3.4646
X7.2441Y-5.2362
T0
M30
